/*
 * Pure emission logic for the operation registry (Story 1.3, AD-3).
 *
 * Snapshot in -> generated module contents out. No filesystem, no env, no
 * side effects: scripts/generate-registry.ts is the only writer, and tests
 * exercise this module directly against fixture snapshots (including the
 * byte-determinism invariant behind the registry:check regen-diff).
 */
import { z } from "zod";

import {
  AGGREGATE_EXECUTION_TOOLS,
  resolveEffectClass,
} from "../lib/registry/effect-class.ts";
import {
  buildInputSchema,
  buildSystemInputSchema,
  compileFieldSpecs,
} from "../lib/registry/field-schema.ts";
import type { SnapshotConfigField } from "../lib/registry/field-schema.ts";
import {
  computeFingerprint,
  computeSnapshotId,
} from "../lib/registry/fingerprint.ts";
import { encodeToolName, OPENAI_TOOL_NAME_PATTERN } from "../lib/registry/tool-name.ts";
import type {
  IntegrationInfo,
  OperationEntry,
  OutputField,
} from "../lib/registry/types.ts";

export type SnapshotAction = {
  id: string;
  kind: "plugin" | "system";
  integration: string;
  slug?: string;
  label: string;
  description: string;
  category: string;
  requiresCredentials: boolean;
  credentialIntegrationType?: string;
  docUrl?: string;
  configFields: SnapshotConfigField[];
  outputFields?: OutputField[];
  outputSchema?: Record<string, unknown>;
  protocolType?: "read" | "write";
  systemFields?: {
    requiredFields: Record<string, string>;
    optionalFields: Record<string, string>;
  };
  behavior?: string;
  sourceHandles?: string[];
};

export type Snapshot = {
  source_repo: string;
  source_commit: string;
  source_branch?: string;
  extracted_at: string;
  action_count: number;
  credential_gated_count: number;
  snapshot_id: string;
  integrations: Record<string, IntegrationInfo>;
  actions: SnapshotAction[];
};

// Non-relitigable platform counts (AGENTS.md): a mismatch is a hard failure.
const EXPECTED_ACTION_COUNT = 442;
const EXPECTED_CREDENTIAL_GATED_COUNT = 139;
const EXPECTED_SYSTEM_IDS = [
  "Collect",
  "Condition",
  "Database Query",
  "For Each",
  "HTTP Request",
];

// FR8 bespoke carve-outs (epics.md): the 5 schema-less control-flow
// primitives (never the degraded stub) and the Solana value-movers. All other
// ops ride the generic-card floor; bespoke money-movers arrive in Epic 2.
const BESPOKE_OP_IDS = new Set([
  ...EXPECTED_SYSTEM_IDS,
  "web3/transfer-spl-token",
  "web3/call-solana-program-anchor",
  "web3/send-raw-solana-instruction",
]);

const GENERATED_BANNER =
  "// DO NOT EDIT -- generated by scripts/generate-registry.ts from" +
  "\n// lib/registry/vendor/configfields.snapshot.json (pnpm registry:generate)." +
  "\n// Hand-edits are rejected by the CI regen-diff (pnpm registry:check).\n";

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(canonicalize);
  }
  if (value !== null && typeof value === "object") {
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      const entry = (value as Record<string, unknown>)[key];
      if (entry !== undefined) {
        sorted[key] = canonicalize(entry);
      }
    }
    return sorted;
  }
  return value;
}

function embed(value: unknown): string {
  return JSON.stringify(canonicalize(value), null, 2);
}

/** "aave-v3" -> "aaveV3": a deterministic identifier for barrel imports. */
function moduleIdentifier(integration: string): string {
  const camel = integration.replace(/-([a-z0-9])/g, (_match, char: string) =>
    char.toUpperCase(),
  );
  // Guarantee a valid JS identifier for the barrel import: replace any
  // non-identifier char and prefix a leading digit ("1inch" / "0x" would emit
  // `import { ops as 1inch }` - a syntax error in the generated index).
  const safe = camel.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[0-9]/.test(safe) ? `_${safe}` : safe;
}

function buildEntry(action: SnapshotAction): OperationEntry {
  const effectClass = resolveEffectClass(action);
  const toolName = encodeToolName(action.id);
  if (!OPENAI_TOOL_NAME_PATTERN.test(toolName)) {
    throw new Error(
      `Encoded toolName "${toolName}" for op "${action.id}" violates the OpenAI pattern`,
    );
  }

  const { fields, passthroughDefaults } = compileFieldSpecs(action.configFields);
  const inputSchema = action.systemFields
    ? buildSystemInputSchema(action.systemFields)
    : buildInputSchema(fields);

  // Baked at generation time from the SAME Zod schema the chat tool will use
  // at runtime - the single-source rule AD-3 exists to enforce.
  const realtimeParameters = z.toJSONSchema(inputSchema) as Record<string, unknown>;
  delete realtimeParameters.$schema;

  return {
    opId: action.id,
    toolName,
    kind: action.kind,
    integration: action.integration,
    label: action.label,
    description: action.description,
    category: action.category,
    effectClass,
    needsCredential: action.requiresCredentials,
    ...(action.credentialIntegrationType !== undefined
      ? { credentialIntegrationType: action.credentialIntegrationType }
      : {}),
    rendererKey: action.id,
    renderer: BESPOKE_OP_IDS.has(action.id) ? "bespoke" : "generic",
    fingerprint: computeFingerprint({
      configFields: action.configFields,
      effectClass,
      ...(action.systemFields !== undefined
        ? { systemFields: action.systemFields }
        : {}),
    }),
    fields,
    passthroughDefaults,
    realtimeParameters,
    ...(action.outputFields !== undefined ? { outputFields: action.outputFields } : {}),
    ...(action.outputSchema !== undefined ? { outputSchema: action.outputSchema } : {}),
    ...(action.protocolType !== undefined ? { protocolType: action.protocolType } : {}),
    ...(action.systemFields !== undefined
      ? {
          systemFields: {
            ...action.systemFields,
            ...(action.behavior !== undefined ? { behavior: action.behavior } : {}),
            ...(action.sourceHandles !== undefined
              ? { sourceHandles: action.sourceHandles }
              : {}),
          },
        }
      : {}),
  };
}

function validateSnapshot(snapshot: Snapshot): void {
  if (snapshot.actions.length !== EXPECTED_ACTION_COUNT) {
    throw new Error(
      `Snapshot action count ${snapshot.actions.length} != ${EXPECTED_ACTION_COUNT} - ` +
        "the AGENTS.md counts are non-relitigable; re-verify the snapshot.",
    );
  }
  if (snapshot.action_count !== snapshot.actions.length) {
    throw new Error(
      `Snapshot header action_count ${snapshot.action_count} disagrees with body`,
    );
  }
  const credentialGated = snapshot.actions.filter(
    (action) => action.requiresCredentials === true,
  ).length;
  if (
    credentialGated !== EXPECTED_CREDENTIAL_GATED_COUNT ||
    snapshot.credential_gated_count !== credentialGated
  ) {
    throw new Error(
      `Credential-gated count mismatch: header ${snapshot.credential_gated_count}, ` +
        `body ${credentialGated}, expected ${EXPECTED_CREDENTIAL_GATED_COUNT}`,
    );
  }
  const systemIds = snapshot.actions
    .filter((action) => action.kind === "system")
    .map((action) => action.id)
    .sort();
  if (JSON.stringify(systemIds) !== JSON.stringify(EXPECTED_SYSTEM_IDS)) {
    throw new Error(
      `System primitives changed: expected [${EXPECTED_SYSTEM_IDS.join(", ")}], ` +
        `got [${systemIds.join(", ")}]`,
    );
  }
  // Integrity: the snapshot id must recompute from the body - this also pins
  // the dump script's canonical serialization to lib/registry/fingerprint.ts.
  const recomputed = computeSnapshotId(snapshot);
  if (recomputed !== snapshot.snapshot_id) {
    throw new Error(
      `Snapshot id mismatch: header ${snapshot.snapshot_id}, recomputed ${recomputed}. ` +
        "The snapshot was hand-edited or the canonical serialization drifted.",
    );
  }
}

/**
 * Build all generated module contents from a validated snapshot.
 * Byte-deterministic: same snapshot -> byte-identical file map.
 */
export function emitRegistryFiles(snapshot: Snapshot): Map<string, string> {
  validateSnapshot(snapshot);

  const entriesByIntegration = new Map<string, OperationEntry[]>();
  const toolNameToOpId: Record<string, string> = {};
  const opIdToToolName: Record<string, string> = {};

  const reservedToolNames = new Set(Object.keys(AGGREGATE_EXECUTION_TOOLS));
  for (const action of [...snapshot.actions].sort((a, b) =>
    a.id < b.id ? -1 : 1,
  )) {
    const entry = buildEntry(action);
    if (toolNameToOpId[entry.toolName] !== undefined) {
      throw new Error(
        `toolName collision: "${entry.toolName}" maps to both ` +
          `"${toolNameToOpId[entry.toolName]}" and "${entry.opId}"`,
      );
    }
    if (reservedToolNames.has(entry.toolName)) {
      throw new Error(
        `toolName "${entry.toolName}" collides with an aggregate execution tool`,
      );
    }
    toolNameToOpId[entry.toolName] = entry.opId;
    opIdToToolName[entry.opId] = entry.toolName;
    const bucket = entriesByIntegration.get(entry.integration) ?? [];
    bucket.push(entry);
    entriesByIntegration.set(entry.integration, bucket);
  }

  const files = new Map<string, string>();
  const integrationNames = [...entriesByIntegration.keys()].sort();

  for (const integration of integrationNames) {
    const ops: Record<string, OperationEntry> = {};
    for (const entry of entriesByIntegration.get(integration) as OperationEntry[]) {
      ops[entry.opId] = entry;
    }
    files.set(
      `${integration}.ts`,
      `${GENERATED_BANNER}import type { OperationEntry } from "../types.ts";\n\n` +
        `export const ops: Record<string, OperationEntry> = ${embed(ops)};\n`,
    );
  }

  const integrations: Record<string, IntegrationInfo> = {
    ...snapshot.integrations,
    // The 5 control-flow primitives are not a plugin; give their family a
    // registry-owned label so Story 1.7's categories cover all 442.
    system: {
      label: "System",
      description: "Workflow control-flow and system primitives.",
    },
  };

  files.set(
    "meta.ts",
    `${GENERATED_BANNER}import type { IntegrationInfo, RegistryMeta } from "../types.ts";\n\n` +
      `export const registryMeta: RegistryMeta = ${embed({
        snapshotId: snapshot.snapshot_id,
        sourceCommit: snapshot.source_commit,
        actionCount: snapshot.actions.length,
      })};\n\n` +
      `export const integrations: Record<string, IntegrationInfo> = ${embed(integrations)};\n\n` +
      `export const toolNameToOpId: Record<string, string> = ${embed(toolNameToOpId)};\n\n` +
      `export const opIdToToolName: Record<string, string> = ${embed(opIdToToolName)};\n`,
  );

  const imports = integrationNames
    .map(
      (integration) =>
        `import { ops as ${moduleIdentifier(integration)} } from "./${integration}.ts";`,
    )
    .join("\n");
  const spreads = integrationNames
    .map((integration) => `  ...${moduleIdentifier(integration)},`)
    .join("\n");
  files.set(
    "index.ts",
    `${GENERATED_BANNER}import type { OperationEntry } from "../types.ts";\n\n` +
      `${imports}\n\n` +
      `export const ops: Record<string, OperationEntry> = {\n${spreads}\n};\n\n` +
      `export { registryMeta, integrations, toolNameToOpId, opIdToToolName } from "./meta.ts";\n`,
  );

  return files;
}
